OrdererOrgs:
  - Name: Orderer
    Domain: identitysystem.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  # Identity Provider Organization
  - Name: IdentityProvider
    Domain: idprovider.identitysystem.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  # Verifier Organization
  - Name: Verifier
    Domain: verifier.identitysystem.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  # User Organization
  - Name: User
    Domain: user.identitysystem.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
