# Sets up the 3 orgs in the network

# CAPABILITIES
Capabilities:
  Application: &ApplicationCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Channel: &ChannelCapabilities
    V2_0: true

# ORGANIZATIONS
Organizations:
  - &Orderer
    Name: Orderer
    ID: OrdererMSP
    MSPDir: ./crypto-config/ordererOrganizations/natuni.edu/msp
    Policies: &OrdererPolicies
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
  - &Natuni
    Name: Natuni
    ID: NatuniMSP
    MSPDir: ./crypto-config/peerOrganizations/natuni.edu/msp
    Policies: &NatuniPolicies
      Readers:
        Type: Signature
        Rule: "OR('NatuniMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('NatuniMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('NatuniMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('NatuniMSP.member')"
    AnchorPeers:
      - Host: cit.natuni.edu
        Port: 7051
      - Host: cst.natuni.edu
        Port: 7051
  - &Privateuni
    Name: Privateuni
    ID: PrivateuniMSP
    MSPDir: ./crypto-config/peerOrganizations/privateuni.edu/msp
    Policies: &PrivateuniPolicies
      Readers:
        Type: Signature
        Rule: "OR('PrivateuniMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('PrivateuniMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('PrivateuniMSP.member')"
      Endorsement:
        Type: Signature
        Rule: "OR('PrivateuniMSP.member')"
    AnchorPeers:
      - Host: bus.privateuni.edu
        Port: 7051
  - &Interuni
    Name: Interuni
    ID: InteruniMSP
    MSPDir: ./crypto-config/peerOrganizations/interuni.edu/msp
    Policies: &InteruniPolicies
      Readers:
        Type: Signature
        Rule: "OR('InteruniMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('InteruniMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('InteruniMSP.member')"
      Endorsement:
        Type: Signature
        Rule: "OR('InteruniMSP.member')"
    AnchorPeers:
      - Host: arts.interuni.edu
        Port: 7051

# ORDERER
Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.natuni.edu:7050
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB
  Capabilities:
    !!merge <<: *OrdererCapabilities

# APPLICATION
Application: &ApplicationDefaults
  ACLs: &ACLsDefault
    lscc/ChaincodeExists: /Channel/Application/Readers
    lscc/GetDeploymentSpec: /Channel/Application/Readers
    lscc/GetChaincodeData: /Channel/Application/Readers
    lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
    qscc/GetChainInfo: /Channel/Application/Readers
    qscc/GetBlockByNumber: /Channel/Application/Readers
    qscc/GetBlockByHash: /Channel/Application/Readers
    qscc/GetTransactionByID: /Channel/Application/Readers
    qscc/GetBlockByTxID: /Channel/Application/Readers
    cscc/GetConfigBlock: /Channel/Application/Readers
    cscc/GetConfigTree: /Channel/Application/Readers
    cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers
    peer/Propose: /Channel/Application/Writers
    peer/ChaincodeToChaincode: /Channel/Application/Readers
    event/Block: /Channel/Application/Readers
    event/FilteredBlock: /Channel/Application/Readers
    _lifecycle/CheckCommitReadiness: /Channel/Application/Writers
    _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers
    _lifecycle/QueryChaincodeDefinition: /Channel/Application/Readers
  Policies: &ApplicationDefaultPolicies
    Endorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
  Organizations:
  Capabilities:
    !!merge <<: *ApplicationCapabilities

# CHANNEL
Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities:
    !!merge <<: *ChannelCapabilities

# PROFILES
Profiles:
  NatuniOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - <<: *Orderer
    Consortiums:
      NatuniConsortium:
        Organizations:
          - <<: *Natuni
          - <<: *Privateuni
          - <<: *Interuni
  NatuniChannel:
    <<: *ChannelDefaults
    Consortium: NatuniConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - <<: *Natuni
        - <<: *Privateuni
        - <<: *Interuni